name: salon_user
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_svg: 
  pinput: ^5.0.0
  carousel_slider: ^4.2.1
  # fluttertoast: 
  readmore: ^3.0.0
  easy_date_timeline: 
  smooth_carousel_slider_widget: ^0.0.3
  intl: ^0.18.1
  dotted_line: ^3.2.2
  image_picker: ^1.1.2
  # calendar_view: ^1.2.0
  flutter_week_view: ^1.3.0
  dropdown_button2: ^2.3.9
  dotted_border: ^2.1.0
  vertical_picker: ^0.0.1
  table_calendar:
  encrypt: ^5.0.3
  crypt: ^4.3.1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.3
  firebase_storage: ^12.2.0
  shimmer: ^3.0.0
  cached_network_image:
  get_storage: ^2.1.1
  email_otp: ^3.0.2
  pull_to_refresh: ^2.0.0

  # firebase plugins
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  google_maps_flutter: ^2.6.1
  # geoflutterfire2: 
  #   path: GeoFlutterFire2-master
  geocoding:
  # flutter_geofire: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/dummy/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Regular.ttf
        - asset: assets/fonts/Bold.ttf
        - asset: assets/fonts/Black.ttf
        - asset: assets/fonts/ExtraBold.ttf
        - asset: assets/fonts/ExtraLight.ttf
        - asset: assets/fonts/Light.ttf
        - asset: assets/fonts/Medium.ttf
        - asset: assets/fonts/SemiBold.ttf
