// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTxcJDd6OHZjkDzzAoNnL1zmOCP7aZ-y4',
    appId: '1:212237749630:android:0b1179c91a9f572e52f72f',
    messagingSenderId: '212237749630',
    projectId: 'saloon-ae3be',
    storageBucket: 'saloon-ae3be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB94LrAQV56ZRdgGs-3yuTukl3Vi50ZVGw',
    appId: '1:762438574934:ios:4586a6666f3d58969decf7',
    messagingSenderId: '212237749630',
    projectId: 'ydsusa',
    storageBucket: 'saloon-ae3be.appspot.com',
    iosBundleId: 'com.app.r-wings',
  );
}
